### PR TITLE
Add tls features

### PR DESCRIPTION
**Pull request by NyCodeGHG**
Hi, a friend of mine wants to use this library in a docker container without having to depend on openssl and use rustls instead.
I added feature flags to choose the tls library in reqwest in this PR.
I also added a note to the projects readme.

Have a nice day!

### CODE REVIEW

**Comment by aprimadi** [comment]
Hello, thank you for opening the pull request. Although it seems like a straightforward change. I would like to defer merging this pull request to see if more people needs it.

It seems to me that since reqwest uses openssl by default most people won't need this. But I may be wrong since I haven't used rustls. This library will still be able to be used with Docker by installing openssl.

**Comment by NyCodeGHG** [comment]
The point is, not everyone wants to install openssl, since you can create really small images when you link everything statically into one file. With openssl you still need an os like alpine in the docker image. With rustls you can avoid that.

**Comment by aprimadi** [comment]
I see, that's a good point. What is the base image that doesn't need an OS?

**Comment by NyCodeGHG** [comment]
here is the Dockerfile from my friend: https://github.com/StckOverflw/minecraft-exporter/blob/1a99cca8f7a9befc1edf82da30f5cec210a7e205/Dockerfile#L14-L16

**Comment by FreyMo** [comment]
Actually, it is possible to run a rust binary using this library with `openssl` from `scratch` as well. I do that in my project in a Dockerfile. There are two things you need to do.

1. Add this to your Cargo.toml:
  ```toml
[dependencies]
openssl = { version = "0.10", optional = true }

[features]
vendored-openssl = ["openssl/vendored"]
```
2. In your Dockerfile, add this:
  ```Dockerfile
RUN cargo build --release --bin minecraft_exporter --features vendored-openssl
```

This will statically link `openssl` to your executable. Have fun with the tiny image :)

Nonetheless, I really appreciate the PR as well because now I can get rid of this workaround

**Pull request merged**
